### PR TITLE
Support Leia

### PR DESCRIPTION
**Pull request by baardisk**
The current version won't install on Leia. I have made som small changes so that it is compatible.

### CODE REVIEW

**Comment by aqw** [comment]
Hey @baardisk 

Thanks for the PR. I have two questions:
1) have you used the addon to watch games? Usually GamePass changes their API and thus breaks the addon every off-season. It would be a pleasant surprise if that's not the case (yet) this season.
2) do you want feedback on your PR, or would you rather I just make the needed changes and merge?

---Alex

**Comment by baardisk** [comment]
> Hey @baardisk
> 
> Thanks for the PR. I have two questions:
> 
> 1. have you used the addon to watch games? Usually GamePass changes their API and thus breaks the addon every off-season. It would be a pleasant surprise if that's not the case (yet) this season.
> 2. do you want feedback on your PR, or would you rather I just make the needed changes and merge?
> 
> ---Alex

Hi @aqw ,

1. Yes, I used your original version last year. I used it on Kodi on Android TV. But now that Kodi was updated on my TV it no longer worked. After these changes that I made, I've tried it both on my TV and on my computer where the addon launches and I am able to browse both upcoming and old games and NFL Network. I can also watch game, but I am not able to watch all the content. This was also true last year to a certain extent. I felt maybe that part was worse now, but didn't test that much. After selecting a game or show sometimes nothing happens. I checked my Kodi-log and discovered that it was getting a CURL 22 error on the stream. A HTTP 403 forbidden error that is. I found that it looks like streams from *.akamaized.net fails with the forbidden error. While a video streaming from *.akamaihd.net worked fine. I tried to trace the traffic when starting when of the failed streams from the Gamepass app on my phone.  Not sure if it's the actual stream address, but seemed to be an address at *.akamaitechnologies.com. So the question is why the *.akamaized.net-videos fail. Are they not the correct stream addresses or is it an authentication issue?

2. You can just make the changes and merge if you want. Up to you.

I can try to help out with the addon when I can if you want, but I may need some pointers to get started.

**Comment by kabukimurder** [comment]
Great work @baardisk. Please make this merge happen @aqw

**Comment by usphil** [comment]
I used version 2019-07-01 on Leia LibreElec 9.0.3, now it works very well with replays, but buffering too much with live stream.
I also used version 2018/09/08 on Krypton LibreElec 8.2.5, everything works smooth on both replays and Live 
Hope @baardisk or @aqw fix it soon for Leia.
Thank you very much!

**Comment by ChloeMarieTaylor76** [comment]
Working fine on my Nvidia Shield TV with leia 18.3. On demand works great, nfl network working fine, no buffering issues as mentioned. Will watch a live game this weekend and report back if any issues. Working better than the official Samsung TV app too :)

**Comment by dav-sap** [comment]
@aqw if you are still checking this repo up, its working 2020 as well, and im using international version, only with inputstream adaptive though.

**Pull request merged**
